### ISSUE TITLE
BoundingBox, TextDocument and TimePoint Alignments

### ISSUE THREAD

**Issue by snewman-aa** [clamsproject/app-easyocr-wrapper#2]
### Because

For every `TimeFrame` input, there is a `TimePoint` output for the frame (millisecond) from which the OCR is taken. Every `TimePoint` has several (usually) `BoundingBox` and `TextDocument` pairs which have `Alignment` annotations linking them. Should each annotation from the pair be linked to the `TimePoint` in its own `Alignment` or should just the `BoundingBox` be aligned to the `TimePoint` and the `TextDocument` will be sufficiently connected to the TimePoint through its alignment to the `BoundingBox`?
@keighrim let me know what you think. I know we haven't really had this many Alignments in an app before.

**Comment by keighrim** [comment]
So as defined in the current vocabulary, `Alignment` annotations are only binary, meaning have only two sides. That said, I don't think necessarily think that having ternary alignment constructions (`TimePoint` <-> `BBox` <-> `TextDocument` <-> `TimePoint` as a circle). Hence, I think a simple linear chain `TimePoint` <-> `BBox` <-> `TextDocument` should be enough, keeping all relations and enabling tracing back to originating timing information.

What I'm more concerned is constructing the relation between `TimeFrame` and all others. a `TimePoint` annotation is "sampled" from the time frame in the input MMIF. So should there be an `Alignment` between the `TF` and `TP`?

**Comment by snewman-aa** [comment]
Why not keep the same linear chain `TimeFrame` <-> `TimePoint` <-> `BBox` <-> `TextDocument`?

Also, should we only create TimePoint annotations if there are OCR results for that TimePoint? 
I've run into input MMIFs with TimeFrames whose midframes don't lead to (confident) OCR output. This currently leads to the following annotation: 
`{"@type": "http://mmif.clams.ai/vocabulary/Alignment/v1", "properties": {"source": "tf_2", "target": "tp_2", "id": "al_12"}}, {"@type": "http://mmif.clams.ai/vocabulary/TimePoint/v1", "properties": {"timePoint": 40414, "id": "tp_3"}}`
with no `BBox` and no `TextDoc`

Should we just skip those `TimeFrame` annotations and not include them in the output MMIF or should we create null `BBox` and `TextDoc` to have a record of TimeFrames that led to no OCR output?
